<?php
namespace Life;

use GreatestShowOnEarth\Life\CarbonBaseCreature;

class Vertebrate extends CarbonBaseCreature {

    public function multiplication()
    {
        parent::multiplication(); // TODO: Change the autogenerated stub
    }

    public function substanceExchange()
    {
        // breath

        // urine

        // eating

        // other?
        parent::substanceExchange(); // TODO: Change the autogenerated stub
    }


}
